/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getSession"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["changePassword"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/totp/setup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["setupTOTP"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/totp/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["confirmTOTP"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/totp": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["disableTOTP"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/providers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listProviders"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getDashboard"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/requests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listRequests"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/requests/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ResourceID"];
            };
            cookie?: never;
        };
        get: operations["getRequest"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/usage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getUsageSummary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/system/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getSystemHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/audit-events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listAuditEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/proxies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listProxies"];
        put?: never;
        post: operations["createProxy"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/proxies/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ResourceID"];
            };
            cookie?: never;
        };
        get: operations["getProxy"];
        put?: never;
        post?: never;
        delete: operations["deleteProxy"];
        options?: never;
        head?: never;
        patch: operations["updateProxy"];
        trace?: never;
    };
    "/upstreams": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listUpstreams"];
        put?: never;
        post: operations["createUpstream"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/upstreams/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ResourceID"];
            };
            cookie?: never;
        };
        get: operations["getUpstream"];
        put?: never;
        post?: never;
        delete: operations["deleteUpstream"];
        options?: never;
        head?: never;
        patch: operations["updateUpstream"];
        trace?: never;
    };
    "/accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listAccounts"];
        put?: never;
        post: operations["createAccount"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/accounts/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ResourceID"];
            };
            cookie?: never;
        };
        get: operations["getAccount"];
        put?: never;
        post?: never;
        delete: operations["deleteAccount"];
        options?: never;
        head?: never;
        patch: operations["updateAccount"];
        trace?: never;
    };
    "/accounts/{id}/validate": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ResourceID"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["validateAccount"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/oauth/providers/google": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getGoogleOAuthConfig"];
        put?: never;
        post: operations["createGoogleOAuthConfig"];
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["updateGoogleOAuthConfig"];
        trace?: never;
    };
    "/oauth-attempts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createOAuthAttempt"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/oauth-attempts/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ResourceID"];
            };
            cookie?: never;
        };
        get: operations["getOAuthAttempt"];
        put?: never;
        post?: never;
        delete: operations["cancelOAuthAttempt"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/oauth-attempts/{id}/callback": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ResourceID"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["completeOAuthAttemptCallback"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/model-routes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listModelRoutes"];
        put?: never;
        post: operations["createModelRoute"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/model-routes/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ResourceID"];
            };
            cookie?: never;
        };
        get: operations["getModelRoute"];
        put?: never;
        post?: never;
        delete: operations["deleteModelRoute"];
        options?: never;
        head?: never;
        patch: operations["updateModelRoute"];
        trace?: never;
    };
    "/client-keys": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listClientKeys"];
        put?: never;
        post: operations["createClientKey"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/client-keys/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ResourceID"];
            };
            cookie?: never;
        };
        get: operations["getClientKey"];
        put?: never;
        post?: never;
        delete: operations["revokeClientKey"];
        options?: never;
        head?: never;
        patch: operations["updateClientKey"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ErrorEnvelope: {
            error: {
                code: string;
                message: string;
                request_id: string;
                details?: {
                    [key: string]: unknown;
                };
            };
        };
        LoginRequest: {
            /** Format: password */
            password: string;
            totp_code?: string;
        };
        PasswordChangeRequest: {
            /** Format: password */
            current_password: string;
            /** Format: password */
            new_password: string;
        };
        TOTPCodeRequest: {
            code: string;
        };
        Session: {
            csrf_token: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            idle_expires_at: string;
            /** Format: date-time */
            absolute_expires_at: string;
            totp_enabled: boolean;
        };
        TOTPSetup: {
            secret: string;
            uri: string;
            /** Format: date-time */
            expires_at: string;
        };
        Provider: {
            id: string;
            name: string;
            auth_methods: string[];
            capabilities: string[];
            /** @enum {string} */
            implementation_status: "planned" | "beta" | "stable";
        };
        Dashboard: {
            database_ready: boolean;
            admin_totp_enabled: boolean;
            counts: {
                [key: string]: number;
            };
            warnings: string[];
        };
        RequestRecord: {
            id: string;
            client_key_id: string;
            client_key_name: string;
            protocol: string;
            endpoint_kind: string;
            public_model_id: string;
            provider_id?: string;
            upstream_id?: string;
            account_id?: string;
            status_code: number;
            error_code?: string;
            streamed: boolean;
            /** Format: date-time */
            started_at: string;
            /** Format: date-time */
            first_byte_at?: string;
            /** Format: date-time */
            completed_at: string;
            /** Format: int64 */
            duration_ms: number;
            /** Format: int64 */
            ttft_ms?: number;
            /** Format: int64 */
            request_bytes: number;
            /** Format: int64 */
            response_bytes: number;
            usage: {
                [key: string]: number;
            };
        };
        RequestRecordPage: {
            items: components["schemas"]["RequestRecord"][];
            next_cursor?: string;
        };
        UsageSummary: {
            /** Format: date-time */
            window_start: string;
            /** Format: int64 */
            requests: number;
            /** Format: int64 */
            errors: number;
            /** Format: int64 */
            streamed: number;
            /** Format: int64 */
            input_tokens: number;
            /** Format: int64 */
            output_tokens: number;
            /** Format: int64 */
            cache_read_tokens: number;
            /** Format: int64 */
            reasoning_tokens: number;
        };
        BuildInfo: {
            version: string;
            commit: string;
            build_time: string;
            go_version: string;
        };
        SystemHealth: {
            ready: boolean;
            database_ready: boolean;
            build: components["schemas"]["BuildInfo"];
        };
        MutableResource: {
            id: string;
            /** Format: int64 */
            version: number;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at?: string;
        };
        Proxy: components["schemas"]["MutableResource"] & {
            name: string;
            /** @enum {string} */
            scheme: "http" | "https" | "socks5";
            host: string;
            port: number;
            username_configured: boolean;
            password_configured: boolean;
            tls_server_name?: string;
            allow_insecure_tls: boolean;
            enabled: boolean;
        };
        ProxyRequest: {
            name: string;
            /** @enum {string} */
            scheme: "http" | "https" | "socks5";
            host: string;
            port: number;
            username?: string;
            /** Format: password */
            password?: string;
            tls_server_name?: string;
            allow_insecure_tls: boolean;
            enabled: boolean;
        };
        Upstream: components["schemas"]["MutableResource"] & {
            provider_id: string;
            name: string;
            /** Format: uri */
            base_url: string;
            default_proxy_id?: string;
            allow_private_network: boolean;
            enabled: boolean;
        };
        UpstreamRequest: {
            /** @description Immutable after creation; updates must retain the existing Provider ID. */
            provider_id: string;
            name: string;
            /** Format: uri */
            base_url: string;
            default_proxy_id?: string;
            allow_private_network: boolean;
            enabled: boolean;
        };
        Account: components["schemas"]["MutableResource"] & {
            upstream_id: string;
            name: string;
            /** @enum {string} */
            auth_kind: "api_key" | "oauth";
            /** @enum {string} */
            billing_kind: "subscription" | "metered" | "custom";
            credential_configured: boolean;
            /** Format: date-time */
            credential_expires_at?: string;
            proxy_id?: string;
            /** @enum {string} */
            status: "draft" | "validating" | "active" | "invalid" | "reauth_required" | "disabled";
            priority: number;
            max_concurrency: number;
        };
        AccountRequest: {
            upstream_id: string;
            name: string;
            /** @enum {string} */
            auth_kind: "api_key" | "oauth";
            /**
             * Format: password
             * @description Required when creating an api_key account; omitted for OAuth accounts and to retain an existing API key during update.
             */
            credential?: string;
            /** Format: date-time */
            credential_expires_at?: string;
            proxy_id?: string;
            /** @enum {string} */
            billing_kind: "subscription" | "metered" | "custom";
            /**
             * @description Creation accepts draft or disabled. Updates may retain active only when an already active account keeps the same credential and egress; validation is the only activation path.
             * @enum {string}
             */
            status: "draft" | "active" | "disabled";
            priority?: number;
            max_concurrency?: number;
        };
        GoogleOAuthConfig: components["schemas"]["MutableResource"] & {
            /** @enum {string} */
            provider_id: "google";
            client_id: string;
            client_secret_configured: boolean;
            project_id: string;
            scopes: string[];
            /** Format: uri */
            redirect_uri: string;
            enabled: boolean;
            beta: boolean;
        };
        GoogleOAuthConfigCreateRequest: {
            client_id: string;
            /** Format: password */
            client_secret: string;
            project_id: string;
            enabled: boolean;
        };
        GoogleOAuthConfigUpdateRequest: {
            client_id: string;
            /**
             * Format: password
             * @description Omit to retain the currently configured client secret.
             */
            client_secret?: string;
            project_id: string;
            enabled: boolean;
        };
        OAuthAttemptRequest: {
            account_id: string;
        };
        OAuthCallbackRequest: {
            /** Format: uri */
            callback_url: string;
        };
        OAuthAttempt: {
            id: string;
            /** @enum {string} */
            provider_id: "google";
            account_id: string;
            /** @enum {string} */
            flow_kind: "authorization_code_pkce";
            /** @enum {string} */
            status: "pending" | "exchanging" | "consumed" | "failed" | "cancelled";
            /** Format: uri */
            authorization_url?: string;
            /** Format: date-time */
            expires_at: string;
            /** Format: date-time */
            created_at: string;
            beta: boolean;
        };
        OAuthCompletion: {
            attempt_id: string;
            account: components["schemas"]["Account"];
        };
        RouteCandidate: {
            account_id: string;
            upstream_model_id: string;
            enabled: boolean;
            /** @description Must match the selected account Provider; xAI accounts accept xai or openai compatibility protocol. */
            protocols: ("openai" | "anthropic" | "gemini" | "xai")[];
            capabilities: string[];
        };
        ModelRoute: components["schemas"]["MutableResource"] & {
            public_model_id: string;
            description: string;
            enabled: boolean;
            multiple_candidates_confirmed: boolean;
            candidates: components["schemas"]["RouteCandidate"][];
        };
        ModelRouteRequest: {
            public_model_id: string;
            description: string;
            enabled: boolean;
            confirm_multiple_candidates: boolean;
            candidates: components["schemas"]["RouteCandidate"][];
        };
        ClientKey: components["schemas"]["MutableResource"] & {
            name: string;
            prefix: string;
            /** @enum {string} */
            status: "active" | "disabled" | "revoked";
            /** Format: date-time */
            expires_at?: string;
            /** Format: date-time */
            last_used_at?: string;
        };
        ClientKeyCreateRequest: {
            name: string;
            /** Format: date-time */
            expires_at?: string;
        };
        ClientKeyUpdateRequest: {
            name: string;
            /** @enum {string} */
            status: "active" | "disabled";
            /** Format: date-time */
            expires_at?: string;
        };
        CreatedClientKey: {
            client_key: components["schemas"]["ClientKey"];
            secret: string;
        };
        AuditEvent: {
            id: string;
            event_type: string;
            actor_kind: string;
            actor_id?: string;
            target_kind?: string;
            target_id?: string;
            request_id?: string;
            outcome: string;
            metadata: {
                [key: string]: unknown;
            };
            /** Format: date-time */
            created_at: string;
        };
        ProxyPage: {
            items: components["schemas"]["Proxy"][];
            next_cursor?: string;
        };
        UpstreamPage: {
            items: components["schemas"]["Upstream"][];
            next_cursor?: string;
        };
        AccountPage: {
            items: components["schemas"]["Account"][];
            next_cursor?: string;
        };
        ModelRoutePage: {
            items: components["schemas"]["ModelRoute"][];
            next_cursor?: string;
        };
        ClientKeyPage: {
            items: components["schemas"]["ClientKey"][];
            next_cursor?: string;
        };
        AuditEventPage: {
            items: components["schemas"]["AuditEvent"][];
            next_cursor?: string;
        };
    };
    responses: {
        /** @description Stable safe error envelope */
        Error: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Proxy resource */
        Proxy: {
            headers: {
                ETag: components["headers"]["ETag"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Proxy"];
            };
        };
        /** @description Upstream resource */
        Upstream: {
            headers: {
                ETag: components["headers"]["ETag"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Upstream"];
            };
        };
        /** @description Account resource without credential material */
        Account: {
            headers: {
                ETag: components["headers"]["ETag"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Account"];
            };
        };
        /** @description Google OAuth configuration without client secret material */
        GoogleOAuthConfig: {
            headers: {
                ETag: components["headers"]["ETag"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["GoogleOAuthConfig"];
            };
        };
        /** @description Model route resource */
        ModelRoute: {
            headers: {
                ETag: components["headers"]["ETag"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ModelRoute"];
            };
        };
        /** @description Client key metadata without secret */
        ClientKey: {
            headers: {
                ETag: components["headers"]["ETag"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ClientKey"];
            };
        };
    };
    parameters: {
        CSRF: string;
        IfMatch: string;
        ResourceID: string;
        Limit: number;
        Cursor: string;
    };
    requestBodies: {
        Proxy: {
            content: {
                "application/json": components["schemas"]["ProxyRequest"];
            };
        };
        Upstream: {
            content: {
                "application/json": components["schemas"]["UpstreamRequest"];
            };
        };
        Account: {
            content: {
                "application/json": components["schemas"]["AccountRequest"];
            };
        };
        ModelRoute: {
            content: {
                "application/json": components["schemas"]["ModelRouteRequest"];
            };
        };
    };
    headers: {
        /** @description Mutable resource version */
        ETag: string;
    };
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Authenticated session */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Session"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    logout: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CSRF"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Session revoked */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Error"];
        };
    };
    getSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current session and recoverable in-memory CSRF token */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Session"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    changePassword: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CSRF"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordChangeRequest"];
            };
        };
        responses: {
            /** @description Rotated current session */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Session"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    setupTOTP: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CSRF"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: password */
                    password: string;
                };
            };
        };
        responses: {
            /** @description Pending TOTP secret, returned only during setup */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TOTPSetup"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    confirmTOTP: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CSRF"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TOTPCodeRequest"];
            };
        };
        responses: {
            /** @description Rotated current session */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Session"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    disableTOTP: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CSRF"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: password */
                    password: string;
                    code: string;
                };
            };
        };
        responses: {
            /** @description Rotated current session */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Session"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    listProviders: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Provider descriptors */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["Provider"][];
                    };
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getDashboard: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Control-plane overview */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Dashboard"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    listRequests: {
        parameters: {
            query?: {
                limit?: components["parameters"]["Limit"];
                cursor?: components["parameters"]["Cursor"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Body-free request metadata page */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RequestRecordPage"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getRequest: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ResourceID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Body-free request metadata */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RequestRecord"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getUsageSummary: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Basic usage summary for the trailing 24 hours */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UsageSummary"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getSystemHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description System and build health */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SystemHealth"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    listAuditEvents: {
        parameters: {
            query?: {
                limit?: components["parameters"]["Limit"];
                cursor?: components["parameters"]["Cursor"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Audit event page */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditEventPage"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    listProxies: {
        parameters: {
            query?: {
                limit?: components["parameters"]["Limit"];
                cursor?: components["parameters"]["Cursor"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Proxy page */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProxyPage"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    createProxy: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CSRF"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["Proxy"];
        responses: {
            201: components["responses"]["Proxy"];
            default: components["responses"]["Error"];
        };
    };
    getProxy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ResourceID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Proxy"];
            default: components["responses"]["Error"];
        };
    };
    deleteProxy: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CSRF"];
                "If-Match": components["parameters"]["IfMatch"];
            };
            path: {
                id: components["parameters"]["ResourceID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Error"];
        };
    };
    updateProxy: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CSRF"];
                "If-Match": components["parameters"]["IfMatch"];
            };
            path: {
                id: components["parameters"]["ResourceID"];
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["Proxy"];
        responses: {
            200: components["responses"]["Proxy"];
            default: components["responses"]["Error"];
        };
    };
    listUpstreams: {
        parameters: {
            query?: {
                limit?: components["parameters"]["Limit"];
                cursor?: components["parameters"]["Cursor"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Upstream page */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UpstreamPage"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    createUpstream: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CSRF"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["Upstream"];
        responses: {
            201: components["responses"]["Upstream"];
            default: components["responses"]["Error"];
        };
    };
    getUpstream: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ResourceID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Upstream"];
            default: components["responses"]["Error"];
        };
    };
    deleteUpstream: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CSRF"];
                "If-Match": components["parameters"]["IfMatch"];
            };
            path: {
                id: components["parameters"]["ResourceID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Error"];
        };
    };
    updateUpstream: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CSRF"];
                "If-Match": components["parameters"]["IfMatch"];
            };
            path: {
                id: components["parameters"]["ResourceID"];
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["Upstream"];
        responses: {
            200: components["responses"]["Upstream"];
            default: components["responses"]["Error"];
        };
    };
    listAccounts: {
        parameters: {
            query?: {
                limit?: components["parameters"]["Limit"];
                cursor?: components["parameters"]["Cursor"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Account page */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountPage"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    createAccount: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CSRF"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["Account"];
        responses: {
            201: components["responses"]["Account"];
            default: components["responses"]["Error"];
        };
    };
    getAccount: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ResourceID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Account"];
            default: components["responses"]["Error"];
        };
    };
    deleteAccount: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CSRF"];
                "If-Match": components["parameters"]["IfMatch"];
            };
            path: {
                id: components["parameters"]["ResourceID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Error"];
        };
    };
    updateAccount: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CSRF"];
                "If-Match": components["parameters"]["IfMatch"];
            };
            path: {
                id: components["parameters"]["ResourceID"];
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["Account"];
        responses: {
            200: components["responses"]["Account"];
            default: components["responses"]["Error"];
        };
    };
    validateAccount: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CSRF"];
                "If-Match": components["parameters"]["IfMatch"];
            };
            path: {
                id: components["parameters"]["ResourceID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Account"];
            default: components["responses"]["Error"];
        };
    };
    getGoogleOAuthConfig: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["GoogleOAuthConfig"];
            default: components["responses"]["Error"];
        };
    };
    createGoogleOAuthConfig: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CSRF"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GoogleOAuthConfigCreateRequest"];
            };
        };
        responses: {
            201: components["responses"]["GoogleOAuthConfig"];
            default: components["responses"]["Error"];
        };
    };
    updateGoogleOAuthConfig: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CSRF"];
                "If-Match": components["parameters"]["IfMatch"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GoogleOAuthConfigUpdateRequest"];
            };
        };
        responses: {
            200: components["responses"]["GoogleOAuthConfig"];
            default: components["responses"]["Error"];
        };
    };
    createOAuthAttempt: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CSRF"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OAuthAttemptRequest"];
            };
        };
        responses: {
            /** @description OAuth authorization attempt */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OAuthAttempt"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getOAuthAttempt: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ResourceID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OAuth authorization attempt status */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OAuthAttempt"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    cancelOAuthAttempt: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CSRF"];
            };
            path: {
                id: components["parameters"]["ResourceID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Cancelled */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Error"];
        };
    };
    completeOAuthAttemptCallback: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CSRF"];
            };
            path: {
                id: components["parameters"]["ResourceID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OAuthCallbackRequest"];
            };
        };
        responses: {
            /** @description Completed OAuth account */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OAuthCompletion"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    listModelRoutes: {
        parameters: {
            query?: {
                limit?: components["parameters"]["Limit"];
                cursor?: components["parameters"]["Cursor"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Model route page */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelRoutePage"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    createModelRoute: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CSRF"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["ModelRoute"];
        responses: {
            201: components["responses"]["ModelRoute"];
            default: components["responses"]["Error"];
        };
    };
    getModelRoute: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ResourceID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["ModelRoute"];
            default: components["responses"]["Error"];
        };
    };
    deleteModelRoute: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CSRF"];
                "If-Match": components["parameters"]["IfMatch"];
            };
            path: {
                id: components["parameters"]["ResourceID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Error"];
        };
    };
    updateModelRoute: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CSRF"];
                "If-Match": components["parameters"]["IfMatch"];
            };
            path: {
                id: components["parameters"]["ResourceID"];
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["ModelRoute"];
        responses: {
            200: components["responses"]["ModelRoute"];
            default: components["responses"]["Error"];
        };
    };
    listClientKeys: {
        parameters: {
            query?: {
                limit?: components["parameters"]["Limit"];
                cursor?: components["parameters"]["Cursor"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Client key page */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClientKeyPage"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    createClientKey: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CSRF"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ClientKeyCreateRequest"];
            };
        };
        responses: {
            /** @description Client key and one-time secret */
            201: {
                headers: {
                    ETag: components["headers"]["ETag"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreatedClientKey"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getClientKey: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ResourceID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["ClientKey"];
            default: components["responses"]["Error"];
        };
    };
    revokeClientKey: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CSRF"];
                "If-Match": components["parameters"]["IfMatch"];
            };
            path: {
                id: components["parameters"]["ResourceID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Revoked */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Error"];
        };
    };
    updateClientKey: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CSRF"];
                "If-Match": components["parameters"]["IfMatch"];
            };
            path: {
                id: components["parameters"]["ResourceID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ClientKeyUpdateRequest"];
            };
        };
        responses: {
            200: components["responses"]["ClientKey"];
            default: components["responses"]["Error"];
        };
    };
}
