import type { components } from './schema'

export type Session = components['schemas']['Session']
export type TOTPSetup = components['schemas']['TOTPSetup']
export type Provider = components['schemas']['Provider']
export type Dashboard = components['schemas']['Dashboard']
export type SystemHealth = components['schemas']['SystemHealth']
export type Proxy = components['schemas']['Proxy']
export type ProxyRequest = components['schemas']['ProxyRequest']
export type ProxyPage = components['schemas']['ProxyPage']
export type Upstream = components['schemas']['Upstream']
export type UpstreamRequest = components['schemas']['UpstreamRequest']
export type UpstreamPage = components['schemas']['UpstreamPage']
export type Account = components['schemas']['Account']
export type AccountRequest = components['schemas']['AccountRequest']
export type AccountPage = components['schemas']['AccountPage']
export type RouteCandidate = components['schemas']['RouteCandidate']
export type ModelRoute = components['schemas']['ModelRoute']
export type ModelRouteRequest = components['schemas']['ModelRouteRequest']
export type ModelRoutePage = components['schemas']['ModelRoutePage']
export type ClientKey = components['schemas']['ClientKey']
export type ClientKeyPage = components['schemas']['ClientKeyPage']
export type CreatedClientKey = components['schemas']['CreatedClientKey']
export type AuditEvent = components['schemas']['AuditEvent']
export type AuditEventPage = components['schemas']['AuditEventPage']
